"""Human-readable potion descriptions for the state encoder.

Sibling of `../card_data/card_text.py` and `../relic_data/relic_text.py`, for potions.
The engine stores no potion display text; this module is the lookup:
`Potion name -> {text, rarity, requires_target, ...}`, loaded from `potion_data.json`
(generated by `build_potion_data.py` from the engine headers + authored text).

Scope is the Ironclad potion pool (33). Other classes are excluded.

    from potion_text import describe_potion, potion_glossary, get_potion_text

    describe_potion(potion)          # 'Fire Potion (Common): Deal 20 damage to target enemy.'
    potion_glossary(gc.potions)      # dedup'd block, empty slots skipped
    get_potion_text(potion)          # just the effect text

`potion` may be an sts `Potion` enum (from `gc.potions` / `bc.potions`) or the id
string ('FIRE_POTION'). Empty slots (`EMPTY_POTION_SLOT` / `INVALID`) are recognized
and skipped by the glossary.
"""
import json
from pathlib import Path

_DATA_PATH = Path(__file__).resolve().parent / "potion_data.json"

with _DATA_PATH.open(encoding="utf-8") as _f:
    POTION_DATA: dict[str, dict] = json.load(_f)

EMPTY_SLOTS = {"EMPTY_POTION_SLOT", "INVALID"}


def _resolve(potion) -> str:
    """Normalize any accepted potion form to its id string.

    Accepts an sts `Potion` enum (has `.name`) or a plain string. Potions from
    `gc.potions` are bare enum values, not wrapped objects, so there's no `.id`.
    """
    name = getattr(potion, "name", potion)   # Potion enum -> 'FIRE_POTION'; else assume str
    return str(name).upper()


def is_empty(potion) -> bool:
    """True for an empty potion slot (or INVALID)."""
    return _resolve(potion) in EMPTY_SLOTS


def get(potion) -> dict | None:
    """Raw data dict for a potion, or None if empty/outside our scope."""
    return POTION_DATA.get(_resolve(potion))


def get_potion_text(potion) -> str:
    """Just the effect text. Returns '' for an empty slot or out-of-scope potion."""
    data = POTION_DATA.get(_resolve(potion))
    return data["text"] if data else ""


def describe_potion(potion) -> str:
    """One line: 'Fire Potion (Common): Deal 20 damage to target enemy.'

    Returns '(empty slot)' for empty slots and falls back to the raw id for anything
    else outside our scope, so it's always safe to call.
    """
    pid = _resolve(potion)
    if pid in EMPTY_SLOTS:
        return "(empty slot)"
    data = POTION_DATA.get(pid)
    if data is None:
        return pid  # out-of-scope potion (e.g. another class's): at least name it
    rarity = data["rarity"].capitalize()
    return f"{data['name']} ({rarity}): {data['text']}"


def potion_glossary(potions, header: str | None = None) -> str:
    """A de-duplicated description block for a collection of potions.

    Empty slots are skipped, and each distinct potion is described once in first-seen
    order (a belt has multiple slots that can hold the same potion).
    """
    seen: set[str] = set()
    lines: list[str] = []
    for p in potions:
        pid = _resolve(p)
        if pid in EMPTY_SLOTS or pid in seen:
            continue
        seen.add(pid)
        lines.append(describe_potion(p))
    body = "\n".join(f"- {ln}" for ln in lines)
    return f"{header}\n{body}" if header else body


if __name__ == "__main__":
    print(describe_potion("FIRE_POTION"))
    print(describe_potion("BLOOD_POTION"))
    print(describe_potion("ENTROPIC_BREW"))
    print(describe_potion("EMPTY_POTION_SLOT"))

    class _FakePotion:  # mimics the sts Potion enum's .name
        def __init__(self, name): self.name = name

    slots = [_FakePotion("FIRE_POTION"), _FakePotion("EMPTY_POTION_SLOT"),
             _FakePotion("FIRE_POTION"), _FakePotion("BLOCK_POTION")]
    print("\n" + potion_glossary(slots, header="Potions:"))
    print(f"\nLoaded {len(POTION_DATA)} potions.")
